### ISSUE TITLE
Create Amp Pivot Subsystem

### ISSUE THREAD

**Issue by Spenceroni-Pepperoni** [Robotiators-888/2024Season#9]
Include in the subsystem:
2 Spark Maxes

- Pivoting motor that has a limit switch for maximum rotation position
- Roller motor that handles spinning at a velocity defined in the Constants file and is triggered when pivot is in deployed state. 

Include Smartdashboard puts:

-  When the amp pivot is deployed and retracted triggered by two separate limit switched

**Comment by KevinH45** [comment]
adsd
